// <auto-generated />
using FIADbContext.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FIADbContext.Migrations
{
    [DbContext(typeof(FIAContext))]
    [Migration("20220203212438_CreateCodeSecondMigration")]
    partial class CreateCodeSecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FIADbContext.Model.DTO.EnterpriseDbDTO", b =>
                {
                    b.Property<string>("TIN")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LegalAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TIN");

                    b.ToTable("Enterprise");
                });

            modelBuilder.Entity("FIADbContext.Model.DTO.FinancialResultDbDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Consumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EnterpriseTIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Enterprise");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseTIN");

                    b.ToTable("FinancialResult");
                });

            modelBuilder.Entity("FIADbContext.Model.DTO.FinancialResultDbDTO", b =>
                {
                    b.HasOne("FIADbContext.Model.DTO.EnterpriseDbDTO", "Enterprise")
                        .WithMany("FinancialResults")
                        .HasForeignKey("EnterpriseTIN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("FIADbContext.Model.DTO.EnterpriseDbDTO", b =>
                {
                    b.Navigation("FinancialResults");
                });
#pragma warning restore 612, 618
        }
    }
}
